server:
  port: 8580

logging:
  level:
    org:
      springframework:
        web:
          DEBUG

spring:
  datasource:
    url: ${DATABASE_SERVER:jdbc:h2:file:~/projects/h2-db/quiz-app-user-db}
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false